/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PostLoginRequest ログインリクエスト
type PostLoginRequest struct {
	// ユーザー名
	Name string `json:"name"`
	// パスワード
	Password string `json:"password"`
}
