/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package traq

import (
	"time"
)

// ChannelViewer チャンネル閲覧者情報
type ChannelViewer struct {
	// ユーザーUUID
	UserId string           `json:"userId"`
	State  ChannelViewState `json:"state"`
	// 更新日時
	UpdatedAt time.Time `json:"updatedAt"`
}
