/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// MessageStamp メッセージに押されたスタンプ
type MessageStamp struct {
	// ユーザーUUID
	UserId string `json:"userId"`
	// スタンプUUID
	StampId string `json:"stampId"`
	// スタンプ数
	Count int32 `json:"count"`
	// スタンプが最初に押された日時
	CreatedAt time.Time `json:"createdAt"`
	// スタンプが最後に押された日時
	UpdatedAt time.Time `json:"updatedAt"`
}
