/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package traq

// MyChannelViewState 自身のチャンネル閲覧状態
type MyChannelViewState struct {
	// WSセッションの識別子
	Key string `json:"key"`
	// チャンネルUUID
	ChannelId string           `json:"channelId"`
	State     ChannelViewState `json:"state"`
}
