/*
 * traQ API
 *
 * traQ v2 API
 *
 * API version: 2.6.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PostUserGroup struct for PostUserGroup
type PostUserGroup struct {
	// グループ名
	Name string `json:"name"`
	// 説明
	Description string `json:"description,omitempty"`
}
