/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package traq

// PostUserTagRequest ユーザータグ追加リクエスト
type PostUserTagRequest struct {
	// タグ文字列
	Tag string `json:"tag"`
}
