/*
traQ v3

traQ v3 API

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package traq

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the UserDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserDetail{}

// UserDetail ユーザー詳細情報
type UserDetail struct {
	// ユーザーUUID
	Id    string           `json:"id"`
	State UserAccountState `json:"state"`
	// BOTかどうか
	Bot bool `json:"bot"`
	// アイコンファイルUUID
	IconFileId string `json:"iconFileId"`
	// ユーザー表示名
	DisplayName string `json:"displayName"`
	// ユーザー名
	Name string `json:"name" validate:"regexp=^[a-zA-Z0-9_-]{1,32}$"`
	// Twitter ID
	TwitterId string `json:"twitterId" validate:"regexp=^[a-zA-Z0-9_]{0,15}$"`
	// 最終オンライン日時
	LastOnline NullableTime `json:"lastOnline"`
	// 更新日時
	UpdatedAt time.Time `json:"updatedAt"`
	// タグリスト
	Tags []UserTag `json:"tags"`
	// 所属グループのUUIDの配列
	Groups []string `json:"groups"`
	// 自己紹介(biography)
	Bio string `json:"bio"`
	// ホームチャンネル
	HomeChannel NullableString `json:"homeChannel"`
}

type _UserDetail UserDetail

// NewUserDetail instantiates a new UserDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserDetail(id string, state UserAccountState, bot bool, iconFileId string, displayName string, name string, twitterId string, lastOnline NullableTime, updatedAt time.Time, tags []UserTag, groups []string, bio string, homeChannel NullableString) *UserDetail {
	this := UserDetail{}
	this.Id = id
	this.State = state
	this.Bot = bot
	this.IconFileId = iconFileId
	this.DisplayName = displayName
	this.Name = name
	this.TwitterId = twitterId
	this.LastOnline = lastOnline
	this.UpdatedAt = updatedAt
	this.Tags = tags
	this.Groups = groups
	this.Bio = bio
	this.HomeChannel = homeChannel
	return &this
}

// NewUserDetailWithDefaults instantiates a new UserDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserDetailWithDefaults() *UserDetail {
	this := UserDetail{}
	return &this
}

// GetId returns the Id field value
func (o *UserDetail) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserDetail) SetId(v string) {
	o.Id = v
}

// GetState returns the State field value
func (o *UserDetail) GetState() UserAccountState {
	if o == nil {
		var ret UserAccountState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetStateOk() (*UserAccountState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *UserDetail) SetState(v UserAccountState) {
	o.State = v
}

// GetBot returns the Bot field value
func (o *UserDetail) GetBot() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Bot
}

// GetBotOk returns a tuple with the Bot field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetBotOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bot, true
}

// SetBot sets field value
func (o *UserDetail) SetBot(v bool) {
	o.Bot = v
}

// GetIconFileId returns the IconFileId field value
func (o *UserDetail) GetIconFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IconFileId
}

// GetIconFileIdOk returns a tuple with the IconFileId field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetIconFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IconFileId, true
}

// SetIconFileId sets field value
func (o *UserDetail) SetIconFileId(v string) {
	o.IconFileId = v
}

// GetDisplayName returns the DisplayName field value
func (o *UserDetail) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *UserDetail) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetName returns the Name field value
func (o *UserDetail) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserDetail) SetName(v string) {
	o.Name = v
}

// GetTwitterId returns the TwitterId field value
func (o *UserDetail) GetTwitterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TwitterId
}

// GetTwitterIdOk returns a tuple with the TwitterId field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetTwitterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TwitterId, true
}

// SetTwitterId sets field value
func (o *UserDetail) SetTwitterId(v string) {
	o.TwitterId = v
}

// GetLastOnline returns the LastOnline field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *UserDetail) GetLastOnline() time.Time {
	if o == nil || o.LastOnline.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastOnline.Get()
}

// GetLastOnlineOk returns a tuple with the LastOnline field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserDetail) GetLastOnlineOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastOnline.Get(), o.LastOnline.IsSet()
}

// SetLastOnline sets field value
func (o *UserDetail) SetLastOnline(v time.Time) {
	o.LastOnline.Set(&v)
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UserDetail) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UserDetail) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetTags returns the Tags field value
func (o *UserDetail) GetTags() []UserTag {
	if o == nil {
		var ret []UserTag
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetTagsOk() ([]UserTag, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *UserDetail) SetTags(v []UserTag) {
	o.Tags = v
}

// GetGroups returns the Groups field value
func (o *UserDetail) GetGroups() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetGroupsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *UserDetail) SetGroups(v []string) {
	o.Groups = v
}

// GetBio returns the Bio field value
func (o *UserDetail) GetBio() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bio
}

// GetBioOk returns a tuple with the Bio field value
// and a boolean to check if the value has been set.
func (o *UserDetail) GetBioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bio, true
}

// SetBio sets field value
func (o *UserDetail) SetBio(v string) {
	o.Bio = v
}

// GetHomeChannel returns the HomeChannel field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UserDetail) GetHomeChannel() string {
	if o == nil || o.HomeChannel.Get() == nil {
		var ret string
		return ret
	}

	return *o.HomeChannel.Get()
}

// GetHomeChannelOk returns a tuple with the HomeChannel field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserDetail) GetHomeChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HomeChannel.Get(), o.HomeChannel.IsSet()
}

// SetHomeChannel sets field value
func (o *UserDetail) SetHomeChannel(v string) {
	o.HomeChannel.Set(&v)
}

func (o UserDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["state"] = o.State
	toSerialize["bot"] = o.Bot
	toSerialize["iconFileId"] = o.IconFileId
	toSerialize["displayName"] = o.DisplayName
	toSerialize["name"] = o.Name
	toSerialize["twitterId"] = o.TwitterId
	toSerialize["lastOnline"] = o.LastOnline.Get()
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["tags"] = o.Tags
	toSerialize["groups"] = o.Groups
	toSerialize["bio"] = o.Bio
	toSerialize["homeChannel"] = o.HomeChannel.Get()
	return toSerialize, nil
}

func (o *UserDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"state",
		"bot",
		"iconFileId",
		"displayName",
		"name",
		"twitterId",
		"lastOnline",
		"updatedAt",
		"tags",
		"groups",
		"bio",
		"homeChannel",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserDetail := _UserDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserDetail)

	if err != nil {
		return err
	}

	*o = UserDetail(varUserDetail)

	return err
}

type NullableUserDetail struct {
	value *UserDetail
	isSet bool
}

func (v NullableUserDetail) Get() *UserDetail {
	return v.value
}

func (v *NullableUserDetail) Set(val *UserDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableUserDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableUserDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserDetail(val *UserDetail) *NullableUserDetail {
	return &NullableUserDetail{value: val, isSet: true}
}

func (v NullableUserDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
