/*
traQ v3

traQ v3 API

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package traq

import (
	"encoding/json"
)

// checks if the QallMetadataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QallMetadataResponse{}

// QallMetadataResponse struct for QallMetadataResponse
type QallMetadataResponse struct {
	// ルームに関連付けられたカスタム属性
	Metadata *string `json:"metadata,omitempty"`
}

// NewQallMetadataResponse instantiates a new QallMetadataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQallMetadataResponse() *QallMetadataResponse {
	this := QallMetadataResponse{}
	return &this
}

// NewQallMetadataResponseWithDefaults instantiates a new QallMetadataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQallMetadataResponseWithDefaults() *QallMetadataResponse {
	this := QallMetadataResponse{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *QallMetadataResponse) GetMetadata() string {
	if o == nil || IsNil(o.Metadata) {
		var ret string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QallMetadataResponse) GetMetadataOk() (*string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *QallMetadataResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given string and assigns it to the Metadata field.
func (o *QallMetadataResponse) SetMetadata(v string) {
	o.Metadata = &v
}

func (o QallMetadataResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QallMetadataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableQallMetadataResponse struct {
	value *QallMetadataResponse
	isSet bool
}

func (v NullableQallMetadataResponse) Get() *QallMetadataResponse {
	return v.value
}

func (v *NullableQallMetadataResponse) Set(val *QallMetadataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQallMetadataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQallMetadataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQallMetadataResponse(val *QallMetadataResponse) *NullableQallMetadataResponse {
	return &NullableQallMetadataResponse{value: val, isSet: true}
}

func (v NullableQallMetadataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQallMetadataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
