/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package traq

// VersionFlags struct for VersionFlags
type VersionFlags struct {
	// 有効な外部ログインプロバイダ
	ExternalLogin []string `json:"externalLogin"`
	// ユーザーが自身で新規登録(POST /api/v3/users)可能か
	SignUpAllowed bool `json:"signUpAllowed"`
}
