/*
 * traQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.6.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OAuth2Decide struct {
	// 承諾する場合は\"approve\"
	Submit string `json:"submit"`
}
