/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PatchUserTagRequest ユーザーのタグの編集リクエスト
type PatchUserTagRequest struct {
	// タグのロック状態
	IsLocked bool `json:"isLocked"`
}
