/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package traq

// OAuth2Client OAuth2クライアント情報
type OAuth2Client struct {
	// クライアントUUID
	Id string `json:"id"`
	// クライアント名
	Name string `json:"name"`
	// 説明
	Description string `json:"description"`
	// クライアント開発者UUID
	DeveloperId string `json:"developerId"`
	// 要求スコープの配列
	Scopes []OAuth2Scope `json:"scopes"`
}
