/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package traq

// PostMessageRequest メッセージ投稿リクエスト
type PostMessageRequest struct {
	// メッセージ本文
	Content string `json:"content"`
	// メンション・チャンネルリンクを自動埋め込みするか
	Embed bool `json:"embed,omitempty"`
}
