/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package traq

// WebRtcUserState WebRTC状態
type WebRtcUserState struct {
	// ユーザーUUID
	UserId string `json:"userId"`
	// チャンネルUUID
	ChannelId string `json:"channelId"`
	// セッションの配列
	Sessions []WebRtcUserStateSessions `json:"sessions"`
}
