/*
 * traQ API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.6.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ClipsFolderIdObject struct for ClipsFolderIdObject
type ClipsFolderIdObject struct {
	// フォルダID
	FolderId string `json:"folderId"`
}
