/*
 * traQ v3
 *
 * traQ v3 API
 *
 * API version: 3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package traq

import (
	"time"
)

// UserStats ユーザー統計情報
type UserStats struct {
	// ユーザーの総投稿メッセージ数(削除されたものも含む)
	TotalMessageCount int64 `json:"totalMessageCount"`
	// ユーザーのスタンプ統計情報
	Stamps []UserStatsStamp `json:"stamps"`
	// 統計情報日時
	Datetime time.Time `json:"datetime"`
}
